name: Build .NET 4.0

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: Build solution
        run: |
          "C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe" TopografiaSuite_NET40.sln /p:Configuration=Release
      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: TopografiaSuite_NET40-bin
          path: Topografia.UI.App\bin\Release
